### PR TITLE
Add Simple Read Write Protocol (SRWP)

### PR DESCRIPTION
**Pull request by binqbit**

### CODE REVIEW

**Comment by binqbit** [comment]
In the current project implementation, there is a compatibility issue — the SRWP protocol is not fully compatible with the editor running simultaneously. When the device connects, it automatically sends data from the editor, which creates interference for the SRWP protocol. I haven't had the opportunity to address this problem yet. For now, to build the driver, I've temporarily disabled the editor initialization in the blaustahl.c file. Here's the relevant code:

```cpp
void core1_main(void) {
  sleep_ms(10);

  while (true) {
    // Since editor initialization causes interference,
    // it is temporarily disabled.
    // if (!init_done && tud_cdc_connected()) {
    //   init_done = true;
    //   editor_init();
    // } else {
    editor_yield();
    // }
  }
}
```

This code temporarily resolves the issue, but a more robust solution will be needed in the future for the editor and SRWP protocol to work together efficiently.

**Comment by machdyne** [comment]
Thanks. If I understand the protocol, it ignores everything unless it sees a byte with the value 0x00.

I don't think Blaustahl should be sending 0x00 when it starts up, but maybe it is?

I'll look into this, but there is an issue #12 when building with the latest pico-sdk that I need to debug first.

**Comment by binqbit** [comment]
When the device reads the byte 0x00, it redirects input data processing and then processes the required number of bytes. However, the problem lies in the fact that the device itself sends a data stream during initialization. This disrupts the correct operation of the software as it expects strictly formatted data, but instead receives initialization data from the buffer. I added a channel purge before each SRWP command, but it did not yield the expected result—part of the initialization data still remains in the buffer, which seems strange.

Most likely, this is related to the same issue [#12](https://github.com/machdyne/blaustahl/issues/12), which hinders the normal functioning of the protocol. The current version of the editor somehow disrupts data transmission during initialization. I believe this issue will be automatically resolved when issue #12 is fixed.

**Comment by machdyne** [comment]
I've merged srwp and am using pico-sdk 1.5.1 for now. There seems to be another possibly unrelated USB CDC issue with pico-sdk 2.0.0.

I now see the issue you mentioned, where the test fails with serialport_srwp. However, I am able to write FRAM data using serialport_srwp. I wonder if you're raising DTR before purging. I believe Blaustahl will wait for DTR before the editor initializes and sends output.

I added a simple python script for testing echo but it's not quite working yet either:

https://github.com/machdyne/blaustahl/blob/main/sw/srwp.py

Will look into this more later. Thanks again.

**Comment by LunarLambda** [comment]
Hi, has there been any development on this since?

I was working on adding a 'text mode' interface which prints the contents as 80-column text, with leading nulls replaced with spaces, and trailing nulls being skipped. I considered using the SWRP support instead, but the read command isn't working (the response contains the editor's status line again, and subsequent commands don't seem to work)

I'll add it to the `bs` utility for now.

**Comment by machdyne** [comment]
Hi. SRWP still isn't working along with the editor, but I plan on looking into this again soon. SRWP would be a convenient way to access the data, and it should work on Windows where the composite firmware isn't recognized.

**Comment by machdyne** [comment]
SRWP seems to be working now, @LunarLambda. There were some issues with both the firmware and the Python script. Keep in mind that it's necessary to discard any data in the input buffer before sending commands, to avoid getting the status bar as a result.

**Pull request merged**
